version: '3'
services:
  service:
    build: ../movies_admin/app
    env_file:
      - ../movies_admin/app/.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - service
    ports:
      - "80:80"

  postgres:
    image: postgres:15
    env_file:
      - ../movies_admin/app/.env
    environment:
      POSTGRES_DB: movies_database
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d movies_database" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  static_volume:
  media_volume:

