# Generated by Django 4.2.11 on 2025-09-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_filmwork_certificate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='filmwork',
            constraint=models.Index(fields=['creation_date'], name='film_work_creation_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(fields=('genre', 'film_work'), name='genre_film_work_idx'),
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(fields=('person', 'film_work'), name='person_film_work_idx'),
        ),
    ]
