# Generated by Django 4.2.11 on 2025-09-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_filmwork_film_work_creation_date_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personfilmwork',
            name='person_film_work_idx',
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(fields=('person', 'film_work', 'role'), name='person_film_work_role_idx'),
        ),
    ]
